version: '3'
services:
  web:
    image: ${CUSTOM_IMAGE}
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydatabase
